---

- name: Create a volume
  hosts: all[0]
  become: true
  tasks:
    - name: Generate brick list
      debug:
        msg: "{{ hostvars[item[0]]['ansible_eth0']['ipv4']['address'] }}:/gluster/brick{{ item[1] }}"
      register: bricks
      with_nested:
        - "{{ groups['all'] }}"
        - "{{ range(1, disk_count + 1)|list }}"

    - name: Create volume from glustercli
      shell: "glustercli volume create --name testvol {{ bricks.results|map(attribute='msg')|join(' ') }} --replica 2 --force"
      register: gd2_res
      failed_when: "gd2_res.rc != 0 and 'volume already exists' not in gd2_res.stderr"
