---

- hosts: all
  become: true
  tasks:
    - name: add gluster4 nightly repo
      get_url:
        url: http://artifacts.ci.centos.org/gluster/nightly/master.repo
        dest: /etc/yum.repos.d/gluster-nightly-master.repo

    - name: add glusterd2 nightly repo
      get_url:
        url: http://artifacts.ci.centos.org/gluster/gd2-nightly/gd2-master.repo
        dest: /etc/yum.repos.d/gd2-master.repo

    - name: Install GlusterFS Server
      yum:
        name: glusterfs-server
        state: present

    - name: Install glusterd2
      yum:
        name: glusterd2
        state: present

- import_playbook: backend-setup.yml

- hosts: all
  become: true
  tasks:
    - name: Enable GD2 service and start it
      systemd:
        name: glusterd2
        daemon_reload: yes
        state: started
        enabled: yes
    - pause:
        seconds: 5
- import_playbook: peer-probe.yml
- import_playbook: create-volume-gd2.yml

- hosts: all
  become: true
  tasks:
    - name: Get GD2 secret from VMs for ease of use
      shell: "cat /var/lib/glusterd2/auth"
      register: gd2_secret
    - debug:
        msg: "http://{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}:24007 -- {{ gd2_secret['stdout'] }}"
...
