---

- name: Peer Probe
  hosts: all[0]
  become: true
  tasks:
    - name: Run peer probe
      shell: "glustercli peer add {{ item }}"
      with_items: "{{ groups['all'][1:] }}"
      register: gd2_peeradd
      failed_when: "gd2_peeradd.rc != 0 and 'Peer exists' not in gd2_peeradd.stderr"

